import { Geist, Geist_Mono } from "next/font/google";
import { Josefin_Slab, Julius_Sans_One } from "next/font/google";
import "./globals.css";

// Load the fonts
const josefin = Josefin_Slab({
  subsets: ["latin"],
  weight: ["400"], // you can add more weights if needed
  variable: "--font-josefin",
});

const julius = Julius_Sans_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-julius",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josefin.variable} ${julius.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
